### ISSUE TITLE
SSH Key Pair for Web User

### ISSUE THREAD

**Issue by MikeiLL** [roots/trellis#1259]
* [x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [ x] This request isn't a duplicate of an existing request
* [ x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Would it make sense to have a task that generates a key pair for the web user?

## Motivation

On a new migration, I'm frequently using `rsync` to transfer shared content like the `uploads` directory. This requires me to have an ssh key pair on the new Trellis server. 

```
- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  community.crypto.openssh_keypair:
    path: /home/web/.ssh/id_rsa
  tags: [webkeypair]
```

That's obviously an ignorant approach, but I'm not even sure if the idea makes sense.
