### ISSUE TITLE
`nginx`: `http2` configuration deprecation notice

### ISSUE THREAD

**Issue by strarsis** [roots/trellis#1528]
### Summary

After updating the Ubuntu LTS packages I noticed a `nginx` notice during reload:
`http2" directive is deprecated, use the "http2" directive instead`

The [current `nginx` site configuration](https://github.com/roots/trellis/blob/v1.22.1/roles/wordpress-setup/templates/wordpress-site.conf.j2#L7-L8) use the old, deprecated directive for enabling `http2`:
````
server {
  listen [::]:443 ssl http2;
  listen 443 ssl http2;
````

Instead of using [`http2` in the `listen` directive](https://nginx.org/en/docs/http/ngx_http_core_module.html#listen:~:text=and%20HTTPS%20requests.-,The%20http2%20parameter,-(1.9.5)%20configures%20the), the [`http2` directive](https://nginx.org/en/docs/http/ngx_http_v2_module.html#http2) (`http2 on`) should be used instead:
````
server {
  listen [::]:443 ssl;
  listen 443 ssl;
  http2 on;
````

### Additional context
[Blog post about the deprecation](https://www.f5.com/company/blog/nginx/nginx-plus-r30-released#:~:text=Deprecation%20of%20listen%20%E2%80%A6%20http2%20directive)

**Comment by swalkinshaw** [comment]
The directive was added in 1.25.1 which was released a year ago. But because we use the PPA it should be fine?

**Comment by swalkinshaw** [comment]
@strarsis want to do the PR?

**Comment by strarsis** [comment]
@swalkinshaw: Sure! The addition could require a check whether SSL/TLS is enabled, as `nginx` appears to need TLS/SSL for HTTP1.1 support when HTTP2 is enabled, the corresponding ticket was closed though: https://trac.nginx.org/nginx/ticket/808

So should `http2 on` only be added when `ssl_enabled` is enabled, which would reflect the current behavior - or is http2 to be enabled independently?

**Comment by retlehs** [comment]
https://github.com/h5bp/server-configs-nginx/pull/335

**Comment by strarsis** [comment]
PR ready: https://github.com/roots/trellis/pull/1529

@retlehs: Indeed, it appears that `http3` can be just enabled out of the box for that `nginx` package.
As some may still be hesitant to enabling `HTTP 3` support in `nginx`, the 
option for `HTTP 3` is turned of by default and can be turned on manually.

**Comment by swalkinshaw** [comment]
Closed by https://github.com/roots/trellis/issues/1528

Thanks!

**Comment by strarsis** [comment]
🤔 Additionally to enabling HTTP/3 support in `nginx`, the firewall (besides a potential cloud/hardware firewall) also has to be configured to accept incoming UDP requests on port `443` for HTTP/3/QUIC.
https://github.com/roots/trellis/blob/v1.22.1/group_vars/all/security.yml#L3

**Comment by swalkinshaw** [comment]
@strarsis want to add those as well? 😄 I think the ferm rule can just be added unconditionally since https already is

**Comment by strarsis** [comment]
> can just be added unconditionally since https already is

For HTTPS:
```yml
- name: allow inbound HTTPS
  set_fact:
    ferm_input_list: "{{ ferm_input_list + [ item_to_add ] }}"
  when: ssl_enabled
  vars:
    item_to_add:
      type: dport_accept
      dport: [https]
      filename: nginx_accept_https
````

For HTTP/3 (QUIC):
```yml
- name: allow port UDP/443 for HTTP/3 (QUIC) support
  set_fact:
    ferm_input_list: "{{ ferm_input_list + [ item_to_add ] }}"
  when: nginx_http3_enabled
  vars:
    item_to_add:
      type: dport_accept
      dport: ['443']
      protocol: udp
      filename: nginx_accept_http3
````

Is the potentially improved security worth the added complexity?
