### ISSUE TITLE
Failed to connect to the host via ssh

### ISSUE THREAD

**Issue by wispyco** [roots/trellis#1565]
### Version

1.13.0

### What did you expect to happen?

I have posted in the roots discord with no response, but I think this might actually be a bug. I initially thought it was just configuration on my side, and am open to being wrong about this, but it really seems to be a issue beyond my understanding with trellis and think it might be more an issue with trellis itself than what I have done. Again may be way off base, but I think its more something to do with trellis.

At this step `copy project templates` I get the following. Now initially I was getting this error further down the line at `composer setup` step, but it fails here now. However I have checked ssh is running on my server and port 22 is open firewalls are open to 22 so on.

I also added this so that it would have the chance to retry in ansible.cfg

```
[ssh_connection]
ssh_args = -o ForwardAgent=yes -o ControlMaster=no -o ControlPersist=60s -o HostKeyAlgorithms=ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ssh-rsa
retries = 3
delay = 5
timeout = 60
```

```
TASK [deploy : Copy project templates] *****************************************
task path: /home/runner/work/scbc.bc.ca/scbc.bc.ca/trellis/roles/deploy/tasks/build.yml:17
<5.78.72.167> ESTABLISH SSH CONNECTION FOR USER: web
<5.78.72.167> SSH: EXEC ssh -vvvv -o ForwardAgent=yes -o ControlMaster=no -o ControlPersist=60s -o 
<5.78.72.167> (255, b'', b'OpenSSH_9.6p1 Ubuntu-3ubuntu13.8, OpenSSL 3.0.13 30 Jan 2024\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 5.78.72.167 is address\r\ndebug3: expanded UserKnownHostsFile \'~/.ssh/known_hosts\' -> \'/home/runner/.ssh/known_hosts\'\r\ndebug3: expanded UserKnownHostsFile \'~/.ssh/known_hosts2\' -> \'/home/runner/.ssh/known_hosts2\'\r\ndebug1: Control socket "/home/runner/.ansible/cp/a30e734adc" does not exist\r\ndebug3: channel_clear_timeouts: clearing\r\ndebug3: ssh_connect_direct: entering\r\ndebug1: Connecting to 5.78.72.167 [5.78.72.167] port 22.\r\ndebug3: set_sock_tos: set socket 3 IP_TOS 0x10\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 5.78.72.167 port 22: Connection timed out\r\nssh: connect to host 5.78.72.167 port 22: Connection timed out\r\n')
failed: [5.78.72.167] (item=.env config) => {
    "ansible_loop_var": "item",
    "item": {
        "dest": ".env",
        "mode": "0600",
        "name": ".env config",
        "src": "roles/deploy/templates/env.j2"
    },
    "msg": "Failed to connect to the host via ssh: OpenSSH_9.6p1 Ubuntu-3ubuntu13.8, OpenSSL 3.0.13 30 Jan 2024\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 5.78.72.167 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/runner/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/runner/.ssh/known_hosts2'\r\ndebug1: Control socket \"/home/runner/.ansible/cp/a30e734adc\" does not exist\r\ndebug3: channel_clear_timeouts: clearing\r\ndebug3: ssh_connect_direct: entering\r\ndebug1: Connecting to 5.78.72.167 [5.78.72.167] port 22.\r\ndebug3: set_sock_tos: set socket 3 IP_TOS 0x10\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 5.78.72.167 port 22: Connection timed out\r\nssh: connect to host 5.78.72.167 port 22: Connection timed out",
    "unreachable": true
}
fatal: [5.78.72.167]: UNREACHABLE! => {
    "changed": false,
    "msg": "All items completed",
    "results": [
        {
            "ansible_loop_var": "item",
            "item": {
                "dest": ".env",
                "mode": "0600",
                "name": ".env config",
                "src": "roles/deploy/templates/env.j2"
            },
            "msg": "Failed to connect to the host via ssh: OpenSSH_9.6p1 Ubuntu-3ubuntu13.8, OpenSSL 3.0.13 30 Jan 2024\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 5.78.72.167 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/runner/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/runner/.ssh/known_hosts2'\r\ndebug1: Control socket \"/home/runner/.ansible/cp/a30e734adc\" does not exist\r\ndebug3: channel_clear_timeouts: clearing\r\ndebug3: ssh_connect_direct: entering\r\ndebug1: Connecting to 5.78.72.167 [5.78.72.167] port 22.\r\ndebug3: set_sock_tos: set socket 3 IP_TOS 0x10\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 5.78.72.167 port 22: Connection timed out\r\nssh: connect to host 5.78.72.167 port 22: Connection timed out",
            "unreachable": true
        }
    ],
    "unreachable": true
}
```

I added this check to the pipeline and it returns SSH port is open

```
 - name: Check SSH connectivity
        run: |
          echo "Checking SSH connectivity to server..."
          timeout 5 bash -c "</dev/tcp/5.78.72.167/22" && echo "SSH port is open!" || echo "SSH port is closed or unreachable!"
```

It seems the other ssh connections in the pipeline before this step are working fine.

I have contacted hetzner to see if it's rate limiting.

My QA pipeline is working just fine.

my github action looks like so

```
# Uncomment this deploy job in this file to use the
# https://github.com/roots/setup-trellis-cli GitHub Action
# for deploying this repo to staging when pushing to staging.
#
# Make sure you've set up the following secrets in your repo:
# - TRELLIS_DEPLOY_SSH_PRIVATE_KEY
# - TRELLIS_DEPLOY_SSH_KNOWN_HOSTS
# - ANSIBLE_VAULT_PASSWORD

name: Deploy SCBC site

on:
  workflow_dispatch:
  push:
    branches: [staging]

jobs:
  # example:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Example deploy job
  #       run: echo "This is an example deploy job. Uncomment the deploy job in .github/workflows/deploy.yml to use the roots/setup-trellis-cli GitHub Action for deploying this repo to staging when pushing to main."

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: yarn
          cache-dependency-path: yarn.lock
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.TRELLIS_DEPLOY_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.TRELLIS_DEPLOY_SSH_KNOWN_HOSTS }}
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.TRELLIS_DEPLOY_SSH_PRIVATE_KEY }}
      - uses: roots/setup-trellis-cli@main
        with:
          ansible-vault-password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          repo-token: ${{ secrets.COMPOSER_AUTH_TOKEN }}
      - name: Check SSH connectivity
        run: |
          echo "Checking SSH connectivity to server..."
          timeout 5 bash -c "</dev/tcp/5.78.72.167/22" && echo "SSH port is open!" || echo "SSH port is closed or unreachable!"
      - name: Deploy
        run: cd trellis && trellis deploy staging
```

Please let me know of any other information I can provide and I will provide it

### What actually happens?

In the pipeline ssh fails after some successful connections

### Steps to reproduce

I don't see how it reproducible other than having a trellis roots radicle project setup on hetzner, with 16gb and running ubuntu 24. And deploying and seeing this error.

### System info

Mac OS Sequouia 15.3.1

### Log output

```shell
TASK [deploy : Copy project templates] *****************************************
task path: /home/runner/work/scbc.bc.ca/scbc.bc.ca/trellis/roles/deploy/tasks/build.yml:17
<5.78.72.167> ESTABLISH SSH CONNECTION FOR USER: web
<5.78.72.167> SSH: EXEC ssh -vvvv -o ForwardAgent=yes -o ControlMaster=no -o ControlPersist=60s -o 
<5.78.72.167> (255, b'', b'OpenSSH_9.6p1 Ubuntu-3ubuntu13.8, OpenSSL 3.0.13 30 Jan 2024\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 5.78.72.167 is address\r\ndebug3: expanded UserKnownHostsFile \'~/.ssh/known_hosts\' -> \'/home/runner/.ssh/known_hosts\'\r\ndebug3: expanded UserKnownHostsFile \'~/.ssh/known_hosts2\' -> \'/home/runner/.ssh/known_hosts2\'\r\ndebug1: Control socket "/home/runner/.ansible/cp/a30e734adc" does not exist\r\ndebug3: channel_clear_timeouts: clearing\r\ndebug3: ssh_connect_direct: entering\r\ndebug1: Connecting to 5.78.72.167 [5.78.72.167] port 22.\r\ndebug3: set_sock_tos: set socket 3 IP_TOS 0x10\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 5.78.72.167 port 22: Connection timed out\r\nssh: connect to host 5.78.72.167 port 22: Connection timed out\r\n')
failed: [5.78.72.167] (item=.env config) => {
    "ansible_loop_var": "item",
    "item": {
        "dest": ".env",
        "mode": "0600",
        "name": ".env config",
        "src": "roles/deploy/templates/env.j2"
    },
    "msg": "Failed to connect to the host via ssh: OpenSSH_9.6p1 Ubuntu-3ubuntu13.8, OpenSSL 3.0.13 30 Jan 2024\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 5.78.72.167 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/runner/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/runner/.ssh/known_hosts2'\r\ndebug1: Control socket \"/home/runner/.ansible/cp/a30e734adc\" does not exist\r\ndebug3: channel_clear_timeouts: clearing\r\ndebug3: ssh_connect_direct: entering\r\ndebug1: Connecting to 5.78.72.167 [5.78.72.167] port 22.\r\ndebug3: set_sock_tos: set socket 3 IP_TOS 0x10\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 5.78.72.167 port 22: Connection timed out\r\nssh: connect to host 5.78.72.167 port 22: Connection timed out",
    "unreachable": true
}
fatal: [5.78.72.167]: UNREACHABLE! => {
    "changed": false,
    "msg": "All items completed",
    "results": [
        {
            "ansible_loop_var": "item",
            "item": {
                "dest": ".env",
                "mode": "0600",
                "name": ".env config",
                "src": "roles/deploy/templates/env.j2"
            },
            "msg": "Failed to connect to the host via ssh: OpenSSH_9.6p1 Ubuntu-3ubuntu13.8, OpenSSL 3.0.13 30 Jan 2024\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 5.78.72.167 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/runner/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/runner/.ssh/known_hosts2'\r\ndebug1: Control socket \"/home/runner/.ansible/cp/a30e734adc\" does not exist\r\ndebug3: channel_clear_timeouts: clearing\r\ndebug3: ssh_connect_direct: entering\r\ndebug1: Connecting to 5.78.72.167 [5.78.72.167] port 22.\r\ndebug3: set_sock_tos: set socket 3 IP_TOS 0x10\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 5.78.72.167 port 22: Connection timed out\r\nssh: connect to host 5.78.72.167 port 22: Connection timed out",
            "unreachable": true
        }
    ],
    "unreachable": true
}
```

### Please confirm this isn't a support request.

Yes
