### ISSUE TITLE
Update MariaDB

### ISSUE THREAD

**Issue by paulbrzeski** [roots/trellis#1575]
### Version

1.23.0

### What did you expect to happen?

Completion of "mariadb: Add MariadB PPA" step

### What actually happens?

Fails due to the link being broken - Rackspace no longer hosts the file.

### Steps to reproduce

1. Select a server running Ubuntu 24.04 (noble)
2. Provision that server in full or just the mariadb tags
3. It should fail when trying to add the PPA at https://mirror.rackspace.com/mariadb/repo/10.11/ubuntu, which gets a 403 Forbidden in the browser.

Related past ticket: https://github.com/roots/trellis/pull/1520

### System info

Running on Ubuntu 20.04, provisioning a remote VPS running 24.04 

### Log output

```shell
TASK [mariadb : Add MariaDB PPA] ****************************************************************************************************************************
fatal: [203.29.242.204]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:Failed to fetch https://mirror.rackspace.com/mariadb/repo/10.11/ubuntu/dists/noble/InRelease  403  Forbidden [IP: 119.9.32.73 443], E:The repository 'https://mirror.rackspace.com/mariadb/repo/10.11/ubuntu noble InRelease' is not signed., W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:http://nginx.org/packages/mainline/ubuntu/dists/noble/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details., W:https://ppa.launchpadcontent.net/ondrej/php/ubuntu/dists/noble/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details."}
```

### Please confirm this isn't a support request.

Yes

**Comment by paulbrzeski** [comment]
I believe the mariadb version needs to be bumped to 11.7, but I'm not sure what repercussions that will have.

Source: https://mariadb.org/adjusting-release-model/

**Comment by tziady** [comment]
had similar issues with Rack Space MariaDB Repo. I believe that repo has disappeared or otherwise depreciated. Only commenting to see info.

Cheers,
T

**Comment by dalepgrant** [comment]
Also put together a quick task to get Trellis to clean up APT sources.

```yaml
# roles/common/tasks/clean-apt-sources.yml (new file)
---
- name: Clean stale APT sources from /etc/apt/sources.list.d
  find:
    paths: /etc/apt/sources.list.d
    patterns: '*.list,*.list.save,*.list.distUpgrade'
    use_regex: false
  register: stale_sources
  become: true

- name: Remove stale APT source files
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ stale_sources.files }}"
  when: stale_sources.matched > 0
  become: true
```

Add those tasks just before Trellis updates APT packages
```yaml
# roles/common/tasks/main.yml
- name: Clean old APT sources
  import_tasks: clean-apt-sources.yml
  when: clean_apt_sources | default(false)

- name: Update apt packages
  apt:
    update_cache: yes
```

Enable with 
```yaml
# group_vars/all/main.yml
clean_apt_sources: true
```

@swalkinshaw or @retlehs if that's worth a PR, happy to put one together.
