### ISSUE TITLE
Deploy command hooks

### ISSUE THREAD

**Issue by swalkinshaw** [roots/trellis#305]
Right now our deploy command "hooks" are limited to strings that get passed into the `command` or `shell` module. This means we can't really take advantage of Ansible modules at all.

This leads to issues like https://github.com/roots/trellis/pull/282 with non-ideal solutions.

Instead we could include task files for each hook:

```yaml
# roles/deploy/tasks/main.yml
- name: Run post_finalize_tasks
  include: hooks/post-deploy.yml
```

```yaml
# roles/deploy/tasks/hooks/post-deploy.yml
- name: Restart php-fpm
  shell: sudo php5-fpm reload
  when: not hhvm

- name: Restart hhvm
  shell: sudo hhvm restart
  when: hhvm
```

/cc @CFXd @louim @fullyint
