### ISSUE TITLE
Static resources being served with trailing slashes

### ISSUE THREAD

**Issue by issunboshi** [roots/trellis#465]
Hi,

I'm running into an issue using Trellis to manage my local development environment.

When requesting JS or CSS resources such as this:
https://localhost:3000/app/themes/assets/css/main.css?v=123533

They are being 301 redirected with a trailing slash appended such as this:
https://localhost:3000/app/themes/assets/css/main.css/?v=123533

The resource is then served as 'text/html' meaning it doesn't get interpreted as a CSS or JS file by the browser.

I haven't come across this before using Trellis, but I can only trace this back to how the server is handling requests as the same site on an Apache server is behaving as expected. Is there anything obvious I need to configure?

For reference here is an anonymised version of my /trellis/group_vars/wordpress_sites.tml config:

```
# Documentation: https://roots.io/trellis/docs/local-development-setup/
wordpress_sites:
  abcdefg.com:
    site_hosts:
      - abcdefg.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    site_install: true
    site_title: A company
    admin_user: hello
    admin_password: there
    admin_email: test@test.co.uk
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: true
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://abcdefg.dev
      wp_siteurl: http://abcdefg.dev/wp
      wp_env: development
      db_name: abcdefgs_db
      db_user: abcdefgs_user
      db_password: apassword
```

Thanks
