### ISSUE TITLE
Provisioning Remote Server w/ Remote SQL DB ‘true’ Issues

### ISSUE THREAD

**Issue by RiFi2k** [roots/trellis#563]
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

## Bug report

**Please provide steps to reproduce, including full log output:**

Provisioning a remote server with newest master branch of Trellis with the variable for remote sql set to true.
mysql_remote_database: true
I have tried it with it set to true from first provision (so no mariadb ever installed) and also provisioning first so mariadb gets installed then switching afterwards.

Either way Trellis will always fail when trying to connect to the remote db and will act like it can't find a local database even though db_host is set to an IP address.

Fails with the error "Access denied for root@localhost(using password YES)"

I also tried SSHing into the server and running 'wp db' commands after verifying that the .env file 100% had the REMOTE DB settings loaded in it. Every time it still wants to connect root@localhost

After trying a few things I decided to ssh into the server and install the package
mysql-client, which I don't think ended up helping.
(This is with no mariadb role run ever)

Then I edited /etc/mysql/my.cnf file and changed the variable 'bind-address' from the local ip 127.0.0.1 to my remote IP, then everything worked as expected.

So it seems the Ansible roles are running through the mysql socket which is set to localhost exclusively. Once I changed the bind address like I said I am able to run commands on the remote DB all day.

**Please describe your local environment:**

Ansible version: 2.0.0.2 and also tried 2.0.1.0

OS: Running the Trellis playbook from an Ubuntu 14.04 instance provisioned on Google Cloud Platform

DB Server: Google Cloud SQL

Note: I have successfully completed this exact provisioning numerous times using the same env variables.

**Where did the bug happen? Development or remote servers?**

Remote server, Ubuntu 14.04 Google Cloud Compute Instance

**Please provide a repository or your `wordpress_sites` config (if possible):**

```
  example.com:
    site_hosts:
      - staging.example.com
    local_path: ../example.com
    repo: git@bitbucket.org:example-sites/example.com.git
    branch: master
    db_create: false
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
    env:
      disable_wp_cron: true
      db_host: 104.xxx.xxx.xxx
      db_user: example_staging
      db_name: example_staging
      db_prefix: ex_


  example.com:
    env:
      db_password: 'epic_db_password'
      # Generate your keys here: https://api.wordpress.org/secret-key/1.1/salt/
      pretend my salts are here

```

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

https://discourse.roots.io/t/provisioning-remote-server-w-remote-sql-db-true-issues/

**Other relevant information:**

Like I said as soon as I changed the socket IP it started working perfectly
