### ISSUE TITLE
`reverse_www` filter not working from www to non-www

### ISSUE THREAD

**Issue by ssnepenthe** [roots/trellis#569]
## Submit a feature request or bug report

- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

With a www domain set in `site_hosts`, the `reverse_www` filter seems to be returning the unmodified domain.

**What is the expected or desired behavior?**

Unless I am completely misunderstanding it, `reverse_www` should be returning the non-www version of the domain.

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

Get latest trellis and bedrock:

```
$ mkdir www.testsite.com && cd www.testsite.com
$ git clone --depth=1 git@github.com:roots/trellis.git && rm -rf trellis/.git
$ git clone --depth=1 git@github.com:roots/bedrock.git site && rm -rf site/.git
$ cd trellis && ansible-galaxy install -r requirements.yml
```

edit `group_vars/development/wordpress_sites.yml`:

```
wordpress_sites:
  www.testsite.com:
    site_hosts:
      - www.testsite.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@testsite.dev
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: self-signed
    cache:
      enabled: false
```

And `group_vars/development/vault.yml`:

```
vault_wordpress_sites:
  www.testsite.com:
    admin_password: admin
    env:
      db_password: example_dbpassword
```

Provision dev server:

```
$ vagrant up
```

Inspect nginx config:

```
$ vagrant ssh
$ cat /etc/nginx/sites-available/www.testsite.com.conf
```

Note the `server_name` in the last two `server` blocks:

```
server {
    listen 80;

    server_name www.testsite.dev;

    return 301 https://$host$request_uri;
}
```

Expected server name is `www.testsite.dev testsite.dev`.

```
server {
    listen 443 ssl http2;

    include h5bp/directive-only/ssl.conf;
    include h5bp/directive-only/ssl-stapling.conf;

    ssl_dhparam /etc/nginx/ssl/dhparams.pem;
    ssl_buffer_size 1400; # 1400 bytes to fit in one MTU

    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";

    ssl_certificate         /etc/nginx/ssl/www.testsite.com.cert;
    ssl_trusted_certificate /etc/nginx/ssl/www.testsite.com.cert;
    ssl_certificate_key     /etc/nginx/ssl/www.testsite.com.key;

    server_name www.testsite.dev;

    return 301 $scheme://www.testsite.dev$request_uri;
}
```

Expected server name is `testsite.dev`.

**Please describe your local environment:**

Ansible version: 2.0.1.0

OS: OS X 10.11.4

Vagrant version: 1.8.1

**Where did the bug happen? Development or remote servers?**

Development, untested on remote servers.

**Please provide a repository or your `wordpress_sites` config (if possible):**

See steps to reproduce above, no other changes made to base repo aside from `wordpress_sites` config.

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

Nothing I could find.
