### ISSUE TITLE
Cron job has literal ${WP_HOME}

### ISSUE THREAD

**Issue by jameskraus** [roots/trellis#581]
## Submit a feature request or bug report

- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

---

**What is the current behavior?**

My cron job for my development/production sites contain this line:

*/15 * * * * vagrant curl -k -s ${WP_HOME}/wp/wp-cron.php > /dev/null 2>&1

**What is the expected or desired behavior?**

It should contain my site address (either development or production depending on the env)

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

`vagrant reload --provision` to set up my development site

**Please describe your local environment:**

Ansible version: 2.0.2.0

OS: Windows 10

Vagrant version: 1.8.1

**Where did the bug happen? Development or remote servers?**

Both

**Please provide a repository or your `wordpress_sites` config (if possible):**

development/wordpress_sites.yml
```
wordpress_sites:
  jameskraus.com:
    site_hosts:
      - jameskraus.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: xxxxx@jameskraus.com
    repo: git@bitbucket.org:jamespkraus/jameskraus.com.git # replace with your Git repo URL
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false
```

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

https://discourse.roots.io/t/cron-job-has-literal-wp-home/6635
