### ISSUE TITLE
TASK [wordpress-setup : Create database of sites] goes wrong

### ISSUE THREAD

**Issue by iDuuck** [roots/trellis#587]
## Bug report

Command:
```
ansible-playbook server.yml -e env=staging
```

Log:
```
TASK [wordpress-setup : Create database of sites] ******************************
System info:
  Ansible 2.0.2.0; Darwin
  Trellis at "Require Ansible 2.0.2 and remove deploy_helper"
---------------------------------------------------
The conditional check 'site_uses_local_db and item.value.db_create |
default(True)' failed. The error was: error while evaluating conditional
(site_uses_local_db and item.value.db_create | default(True)): 'dict object'
has no attribute u'theluxuryjournal.com'

The error appears to have been in
'/Users/nick/Development/theluxuryjournal.com/trellis/roles/wordpress-
setup/tasks/database.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: Create database of sites
  ^ here

fatal: [188.166.160.141]: FAILED! => {"failed": true}
	to retry, use: --limit @server.retry
```

**Please describe your local environment:**

Ansible version: ansible 2.0.2.0

OS: 10.10

Vagrant version: Vagrant 1.8.1

**Where did the bug happen? Development or remote servers?**

Remote server

**Please provide a repository or your `wordpress_sites` config (if possible):**

```
# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/staging/vault.yml

wordpress_sites:
  theluxuryjournal.com:
    site_hosts:
      - staging.theluxuryjournal.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: GIT-REPO-HERE # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: staging
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
```
