### ISSUE TITLE
Running server.yml with production environment provisions staging instead

### ISSUE THREAD

**Issue by vercotux** [roots/trellis#595]
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

---

**What is the current behavior?**

Using a fresh digitalocean droppplet I have ran
```ansible-playbook server.yml -e env=production```

What ended up happening is the droppled was provisioned into a staging server instead of a production environment.
On the dropplet, inside _/etc/nginx/sites-enabled/_ only the staging host is present!
The only way around this was to delete the group_vars/staging directory before provisioning.
It appears as if the **env** variable is simply being ignored or somehow overridden by '_staging_'.
Why would this happen? Why is the staging config overriding the production config?

**What is the expected or desired behavior?**

Production environment provisioned.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

Followed this tutorial: http://davekiss.com/develop-wordpress-sites-like-a-goddamn-champion/

* group_vars/production/wordpress_sites.yml:

```yml
wordpress_sites:
  example.co:
    site_hosts:
      - example.co
    local_path: ../site
    repo: git@bitbucket.org:example/example.co.git
    repo_subtree_path: site
    branch: master
    multisite:
      enabled: true
      subdomains: true
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
    env:
      domain_current_site: example.co
      wp_home: https://example.co
      wp_siteurl: https://example.co/wp
```

 * group_vars/staging/wordpress_sites.yml

```yml
wordpress_sites:
  staging.example.co:
    site_hosts:
      - staging.example.co
    local_path: ../site
    repo: git@bitbucket.com:example/example.co.git
    repo_subtree_path: site
    branch: master
    multisite:
      enabled: true
      subdomains: true
    ssl:
      enabled: true
      provider: self-signed
    cache:
      enabled: false
    env:
      domain_current_site: staging.example.co
      wp_home: https://staging.example.co
      wp_siteurl: https://staging.example.co/wp

```

**Please describe your local environment:**

Ansible version:  2.1.0.0
