### ISSUE TITLE
admin-ajax.php: 502 Bad Gateway

### ISSUE THREAD

**Issue by vercotux** [roots/trellis#612]
## Submit a feature request or bug report

- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

---

**What is the current behavior?**

Plugins which rely on admin-ajax.php in the admin dashboard (Appearance --> Widgets) are not working.

**What is the expected or desired behavior?**

Being able to use the admin dashboard for plugins which rely on admin-ajax.php

---

## Bug report

On development (Vagrant) the admin-ajax.php script seems to be broken or otherwise inaccessible

This is the server response when a plugin tries to access *https://example.dev/wp/wp-admin/admin-ajax.php*:

```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

This looks like some sort of issue with nginx.

**Please describe your local environment:**

Ansible version: 2.1.0.0

OS: Ubuntu 16.04 x64

Vagrant version: 1.7.4

**Where did the bug happen? Development or remote servers?**

Development

**Please provide a repository or your `wordpress_sites` config (if possible):**

```
wordpress_sites:
  example.com:
    site_hosts:
      - example.dev
      - example2.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    site_name: Example Site
    admin_email: admin@example.dev
    multisite:
      enabled: true
      subdomains: true
    ssl:
      enabled: true
      provider: self-signed
    cache:
      enabled: false
    env:
      domain_current_site: example.dev
      wp_home: https://example.dev
      wp_siteurl: https://example.dev/wp
```
