### ISSUE TITLE
Home and Site URLs return literal placeholders.

### ISSUE THREAD

**Issue by aaemnnosttv** [roots/trellis#645]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [ ] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

Working from a fresh `roots-example-project`.  Maybe that project is just out of sync?

```
vagrant@roots-example-project:/srv/www/roots-example-project.com/current$ wp option get home
https://${HTTP_HOST}
vagrant@roots-example-project:/srv/www/roots-example-project.com/current$ wp option get siteurl
https://${HTTP_HOST}/wp
vagrant@roots-example-project:/srv/www/roots-example-project.com/current$ wp eval 'echo home_url();'
https://${HTTP_HOST}
https://${HTTP_HOST}vagrant@roots-example-project:/srv/www/roots-example-project.com/current$ wp eval 'echo site_url();'
http://${HTTP_HOST}/wp
```

**What is the expected or desired behavior?**

These commands should return `https://roots-example-project.dev` and `https://roots-example-project.dev/wp` respectively.

---

## Bug report

**Please describe your local environment:**

Ansible version: `2.0.0.2`

OS: El Capitain `10.11.6`

Vagrant version: `1.8.4`

**Where did the bug happen? Development or remote servers?**

Just reproduced locally so far.

**Please provide a repository or your `wordpress_sites` config (if possible):**

```yml
wordpress_sites:
  roots-example-project.com:
    site_hosts:
      - roots-example-project.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@roots-example-project.dev
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: self-signed
    cache:
      enabled: false
```

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

https://discourse.roots.io/t/cron-job-has-literal-wp-home/6635/6
