### ISSUE TITLE
"service not found" in Let's Encrypt renewal job

### ISSUE THREAD

**Issue by joshrickert** [roots/trellis#651]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

---

**What is the current behavior?**

During Let's Encrypt renewal cron job, `service nginx reload` fails with this message:

> /bin/sh: 1: service: not found

**What is the expected or desired behavior?**

nginx should reload after running the renewal script.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

I just provisioned a fresh remote server on Ubuntu 16.04 using Trellis 0.9.8 and Let's Encrypt. When the renewal cron job activated, I received this email:

> **Subject:**
> Cron <root@myserver> cd /var/lib/letsencrypt && ./renew-certs.py && service nginx reload
> **Message:**
> Certificate file /etc/nginx/ssl/letsencrypt/mysite.com.cert already exists
>  The certificate is younger than 60 days. Not creating a new certificate.
>
> /bin/sh: 1: service: not found

So it seems like nginx is not reloading properly after executing the renewal script.

**Please describe your local environment:**

Ansible version: 2.1.1.0
OS: MacOS 10.11.6
Vagrant version: 1.8.5

**Where did the bug happen? Development or remote servers?**

Remote production server.

**Please provide a repository or your `wordpress_sites` config (if possible):**

```
wordpress_sites:
  mysite.com:
    site_hosts:
      - canonical: mysite.com
        redirects:
          - www.mysite.com
          - somethingelse.mysite.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@bitbucket.org:MyAccount/mysite.com.git
    branch: master
    # repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    site_install: true
    site_title: Site title
    db_create: true
    db_import: ../database/mysite_wordpress_prod.sql
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
      duration: 30s
    env:
      disable_wp_cron: true
      db_name: mysite_wordpress_prod
      db_user: myname_wp
      # Define the following variables in group_vars/production/vault.yml
      # db_password:
      # auth_key:
      # secure_auth_key:
      # logged_in_key:
      # nonce_key:
      # auth_salt:
      # secure_auth_salt:
      # logged_in_salt:
      # nonce_salt:

```

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

Not that I can see.
