### ISSUE TITLE
Allow local git repo

### ISSUE THREAD

**Issue by strarsis** [roots/trellis#776]
## Submit a feature request or bug report

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---

**What is the current behavior?**

X Playbook aborts because repo field does contain a path (to a directory).

**What is the expected or desired behavior?**

X Playbook accepts this path and proceeds.

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

X In (staging environment used here) deploy.yml:
````
[...]
    repo: /srv/git/thesite.tld.git
[...]
````

**Please describe your local environment:**

Ansible version: X 2.2.1.0

OS: X Ubuntu 16.04.2 LTS

Vagrant version: X 1.9.1

**Where did the bug happen? Development or remote servers?**

X Development

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

X https://discourse.roots.io/t/trellis-deploy-push-instead-pull/8914/4

Related ansible yaml:
```yaml
- name: Ensure repo is valid
      connection: local
      fail:
        msg: |
          Invalid Git repository.
          Ensure that your site's `repo` variable is defined in `group_vars/{{ env }}/wordpress_sites.yml` and uses the SSH format (example: git@github.com:roots/bedrock.git)
          More info:
          > https://roots.io/trellis/docs/deploys/
      when: project.repo is not defined or not project.repo | match(".*@.*:.*\.git")
````
The regular expression only matches remote URLs with 
username and hostname with path segnent but not just plain paths.
It also enforces URLs that end with .git - which may be best practice but isn't required for using git.
