### ISSUE TITLE
Wrong root domain used as base for nginx multisite config server_name wildcard entry when the main site domain starts by www.

### ISSUE THREAD

**Issue by medfreeman** [roots/trellis#806]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

**What is the current behavior?**

Given this wordpress_sites.yml

```
wordpress_sites:
  example.com:
    site_hosts:
      - canonical: www.example.com
        redirects:
          - example.com
    local_path: ../site
    repo: git@github.com:nickname/example_com.git
    repo_subtree_path: site
    branch: production
    multisite:
      enabled: true
      subdomains: true
    env:
      domain_current_site: example.com
      wp_home: http://www.example.com
      wp_siteurl: http://www.example.com/wp
    ssl:
      enabled: false
    cache:
      enabled: false
```

The nginx configuration of the corresponding 'example.com' site contains : 
```
server_name    www.example.com *.www.example.com ;
```

As seen in [roles/wordpress-setup/templates/wordpress-site.conf.j2 l.8](https://github.com/roots/trellis/blob/32a078ab09ea1fbe25f4daf1319b2a234e233242/roles/wordpress-setup/templates/wordpress-site.conf.j2#L8), the wildcard entry is generated from the 'canonical' host entry.

**What is the expected or desired behavior?**

The nginx configuration of the corresponding 'example.com' should contain : 
```
server_name    www.example.com *.example.com ;
```

The multisite root domain is example.com, and it subsites are available on subdomains of example.com, not www.example.com.
www.example.com is only the canonical url of the main site.

The wildcard entry should be generated from the 'domain_current_site' host entry.

**Comment by medfreeman** [comment]
I'll send a PR when back from lunch.

**Comment by fullyint** [comment]
I don't understand why you would want the primary site in the network to be `example.com` (`domain_current_site: example.com`) if you're redirecting traffic away from `example.com` via:
```
    site_hosts:
      - canonical: www.example.com
        redirects:
          - example.com
```

Any chance the revised config below makes the site behave the way you desire?
```diff
  wordpress_sites:
    example.com:
      site_hosts:
-       - canonical: www.example.com
+       - canonical: example.com
          redirects:
-           - example.com
+           - www.example.com
      local_path: ../site
      repo: git@github.com:nickname/example_com.git
      repo_subtree_path: site
      branch: production
      multisite:
        enabled: true
        subdomains: true
      env:
        domain_current_site: example.com
-       wp_home: http://www.example.com
-       wp_siteurl: http://www.example.com/wp
      ssl:
        enabled: false
      cache:
        enabled: false
```
