### ISSUE TITLE
Feature Request: Gzip static files during deploy

### ISSUE THREAD

**Issue by TangRufus** [roots/trellis#864]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

## Feature Request

Compress WP / plugins static files into `*.gz` files during deploy, i.e. impletement https://discourse.roots.io/t/gzip-sage-assets-in-gulp-task/3115 into normal trellis deploy workflow.

Isn't that gzip enabled already in `nginx.conf`?
Yes, but currently we compress `*.gz` on the fly. If we compress during deploy, we can push compress level to maximum.

**Comment by swalkinshaw** [comment]
Trellis isn't directly tied to Sage so not sure we can do this by default. But we could make it part of this example file: https://github.com/roots/trellis/blob/master/deploy-hooks/build-before.yml

We'd actually only need Ansible itself for this.

Something like:

```yaml
- name: Gzip Sage assets
   archive:
     path: "{{ item }}"
     format: gz
   with_fileglob:
     - "{{ project_local_path }}/web/app/themes/sage/dist/**/*"
```
