### ISSUE TITLE
Feature Request: New SSL provider CloudFlare Origin CA

### ISSUE THREAD

**Issue by TangRufus** [roots/trellis#868]
Generate a cert by cli for `example.com, *.example.com, *.another.com` when this example config is given:

```yaml
wordpress_sites:
  example.com:
    site_hosts:
      - canonical: example.com
        redirects:
          - www.example.com
          - ww2.example.com
          - www.another.com
    ssl:
      enabled: true
      provider: cloudflare
```

It should:
- [ ] add cloudflare package repository https://pkg.cloudflare.com/
- [ ] `root@server# apt-get install cfca`
- [ ] calculate a list of hostnames, e.g.: `example.com, *.example.com, *.another.com`
- [ ] `root@server# CF_API_KEY=XXXXX cfca getcert -hostnames example.com,*.example.com,*.another.com -key-out /etc/nginx/ssl/cloudflare.key -certificate-out /etc/nginx/ssl/cloudflare.pem -overwrite`
- [ ] Update `/etc/nginx/nginx.conf` template

See:
- https://blog.cloudflare.com/cloudflare-ca-encryption-origin/
- https://support.cloudflare.com/hc/en-us/articles/217471977
